package megophone

import "testing"

func Test(t *testing.T) {
	Metaphone("Michael")
	Metaphone("McHugh")
	Metaphone("Chianti")
	Metaphone("Caesar")
	Metaphone("Czerny")
	Metaphone("Bach")
	Metaphone("focaccia")
	Metaphone("accident")
	Metaphone("bacci")
	Metaphone("Mac Gregor")
	Metaphone("edge")
	Metaphone("Edgar")
	Metaphone("Ghiradelli")
	Metaphone("Hugh")
	Metaphone("bough")
	Metaphone("Broughton")
	Metaphone("drought")
	Metaphone("McLaughlin")
	Metaphone("Gough")
	Metaphone("Cagney")
	Metaphone("Tagliaro")
	Metaphone("Danger")
	Metaphone("Germany")
	Metaphone("GIF")
	Metaphone("Vigier")
	Metaphone("John")
	Metaphone("Jankelowicz")
	Metaphone("San Jose")
	Metaphone("Manickaraj")
}
